# Generated by Django 3.2.7 on 2024-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfileprocess',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
