# Generated by Django 3.2.7 on 2024-01-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lvao', '0002_csvfileprocess_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('adress1', models.CharField(max_length=255)),
                ('adress2', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cleaned_adress1', models.CharField(max_length=255)),
                ('cleaned_adress2', models.CharField(blank=True, max_length=255, null=True)),
                ('cleaned_zipcode', models.CharField(max_length=20)),
                ('cleaned_city', models.CharField(max_length=100)),
                ('cleaned_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cleaned_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('csvfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lvao.csvfileprocess')),
            ],
        ),
    ]
