# Generated by Django 3.2.7 on 2024-01-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvao', '0003_csvdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='adress1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='cleaned_adress1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='cleaned_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='cleaned_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='cleaned_long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='cleaned_zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
