# Generated by Django 3.2.7 on 2024-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvao', '0009_csvdata_data_gouv_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='adress1',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='adress2',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='cleaned_address_for_hash',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='cleaned_adress1',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='cleaned_adress2',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='cleaned_gps_for_hash',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
