# Generated by Django 3.2.7 on 2024-01-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvao', '0010_auto_20240103_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='error',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
