# Generated by Django 3.2.7 on 2024-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvao', '0011_csvdata_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfileprocess',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
