# Generated by Django 3.2.7 on 2024-01-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvao', '0012_alter_csvfileprocess_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='data_gouv_json_score',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
