# Generated by Django 3.2.7 on 2024-01-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvao', '0014_auto_20240103_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='data_gouv_json_score',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='data_gouv_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
